import {activeElapsed,serializeRun,startFlags,restartPolicy} from '../server/run-policy.mjs';
/** Sites-only Worker. Trust identity headers ONLY behind the private Sites dispatcher.
 * Never expose this Worker directly on workers.dev or another public origin. */
import {games,roster} from '../public/registry.mjs';
import {VERSION,assert,hash} from '../public/core.mjs';
import {CATALOG,rewardFor} from '../server/economy.mjs';
const security={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'"};
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{...security,'content-type':'application/json'}});
async function readBody(request){const reader=request.body?.getReader();if(!reader)return {};let bytes=0,text='',decoder=new TextDecoder();while(true){const {done,value}=await reader.read();if(done)break;bytes+=value.byteLength;if(bytes>180000){await reader.cancel();throw new Error('Request too large');}text+=decoder.decode(value,{stream:true});}text+=decoder.decode();return text?JSON.parse(text):{};}
export default {async fetch(request,env){try{
 const url=new URL(request.url),user=request.headers.get('oai-authenticated-user-id');
 if(!user){if(url.pathname.startsWith('/api/'))return json({error:'Sign in required'},401);return new Response('<!doctype html><title>Prism Playground · Private</title><h1>Prism Playground</h1><p>This arcade is private.</p><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT</a>',{status:401,headers:{...security,'content-type':'text/html'}});}
 if(!env.DB)return json({error:'Private storage is not configured yet.'},503);
 if(!['GET','HEAD'].includes(request.method)&&((request.headers.get('Origin')&&request.headers.get('Origin')!==url.origin)||request.headers.get('Sec-Fetch-Site')==='cross-site'))return json({error:'Cross-origin request rejected'},403);
 const db=env.DB,stmt=(sql,...args)=>db.prepare(sql).bind(...args),get=(sql,...args)=>stmt(sql,...args).first(),all=async(sql,...args)=>(await stmt(sql,...args).all()).results;
 const own=async id=>{const r=await get('SELECT * FROM runs WHERE id=? AND user_id=?',id,user);assert(r,'Run not found');return r;};
 const view=r=>serializeRun(r,Date.now());
 await stmt('INSERT OR IGNORE INTO profiles(user_id,created_at) VALUES(?,?)',user,new Date().toISOString()).run();
 if(!['GET','HEAD'].includes(request.method)){const n=await get('SELECT COUNT(*) AS n FROM actions JOIN runs ON runs.id=actions.run_id WHERE runs.user_id=? AND actions.timestamp>?',user,Date.now()-60000);assert(n.n<600,'Too many requests. Please wait.');}
 if(url.pathname==='/api/profile'){const p=await get('SELECT * FROM profiles WHERE user_id=?',user);return json({...p,user_id:undefined,equipped:JSON.parse(p.equipped),local:false,catalog:CATALOG,inventory:(await all('SELECT item_id FROM inventory WHERE user_id=?',user)).map(x=>x.item_id),achievements:await all('SELECT achievement,awarded_at FROM achievements WHERE user_id=?',user)});}
 if(url.pathname==='/api/challenges'){const day=new Date().toISOString().slice(0,10);return json({day,game:roster[hash(day)%roster.length].id,difficulty:'normal',completed:(await all('SELECT challenge FROM challenges WHERE user_id=? AND day=?',user,day)).map(x=>x.challenge)});}
 if(url.pathname==='/api/runs'&&request.method==='GET')return json((await all('SELECT * FROM runs WHERE user_id=? ORDER BY started_at DESC LIMIT 1000',user)).map(view));
 if(url.pathname==='/api/runs'&&request.method==='POST'){const b=await readBody(request),g=games[b.game],flags=startFlags(b);assert(g,'Unknown game');assert(['calm','normal','expert'].includes(b.difficulty),'Unknown difficulty');assert(g.meta.modes.includes(b.mode),'Unknown mode');const recent=await get('SELECT COUNT(*) AS n FROM runs WHERE user_id=? AND started_at>?',user,Date.now()-60000);assert(recent.n<60,'Too many new runs. Please wait.');const day=new Date().toISOString().slice(0,10);if(b.daily)assert(roster[hash(day)%roster.length].id===b.game&&b.difficulty==='normal'&&b.mode===g.meta.modes[0],'Daily settings must match');const restart=flags.restart?await own(b.restartId):null,policy=restart?restartPolicy(restart,b):null;let seed,daily=b.daily?day:null;if(b.daily){await stmt('INSERT OR IGNORE INTO daily_seeds VALUES(?,?,?)',day,b.game,crypto.randomUUID()).run();seed=(await get('SELECT seed FROM daily_seeds WHERE day=? AND game=?',day,b.game)).seed;}else if(restart){seed=restart.seed;if(restart.daily===day&&await get('SELECT 1 FROM daily_seeds WHERE day=? AND game=? AND seed=?',day,b.game,seed))daily=day;}else seed=flags.replay?b.replaySeed:crypto.randomUUID();const practice=policy?policy.practice:b.mode==='practice'||flags.replay,assisted=policy?policy.assisted:0,state=g.create(seed,b.difficulty,b.mode),id=crypto.randomUUID(),now=Date.now();// The eligibility read belongs to the INSERT statement inside D1's atomic batch.
// Concurrent first starts cannot both qualify, even when their earlier reads overlap.
const values=[id,user,b.game,VERSION,b.difficulty,b.mode,seed,now,now,JSON.stringify(state),'playing',practice?1:0,assisted,daily,user,b.game,seed,daily];
const createSql="INSERT INTO runs(id,user_id,game,version,difficulty,mode,seed,started_at,active_since,state,status,practice,assisted,daily) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,CASE WHEN ?<>0 OR (? IS NOT NULL AND EXISTS(SELECT 1 FROM runs WHERE user_id=? AND game=? AND seed=?)) THEN 1 ELSE 0 END,?";
const insert=restart?stmt(createSql+" WHERE EXISTS(SELECT 1 FROM runs WHERE id=? AND user_id=? AND status='playing' AND revision=?)",...values,restart.id,user,restart.revision):stmt(createSql,...values);
const saved=await db.batch([insert,stmt("UPDATE runs SET status='abandoned',ended_at=?,elapsed=elapsed+CASE WHEN active_since IS NULL THEN 0 ELSE MAX(0,?-active_since) END,active_since=NULL,state=json_set(state,'$.status','abandoned'),summary='{\"metric\":\"Abandoned\",\"performance\":0}',reward='{\"xp\":0,\"crystals\":0}' WHERE user_id=? AND status='playing' AND id<>? AND EXISTS(SELECT 1 FROM runs WHERE id=?)",now,now,user,id,id)]);assert(saved[0].meta.changes===1,'Run changed. Reload before restarting.');return json(view(await own(id)),201);}
 const match=url.pathname.match(/^\/api\/runs\/([a-f0-9-]+)(?:\/(actions|export))?$/);if(match){const r=await own(match[1]);if(request.method==='GET'){const result=view(r);if(match[2]==='export'){assert(r.status!=='playing','Finish before exporting');result.actions=(await all('SELECT revision,timestamp,action FROM actions WHERE run_id=? ORDER BY revision',r.id)).map(a=>({...a,action:JSON.parse(a.action)}));}return json(result);}assert(request.method==='POST'&&match[2]==='actions');const b=await readBody(request);assert(typeof b.actionId==='string'&&/^[a-f0-9-]{36}$/.test(b.actionId),'Action ID required');if(await get('SELECT 1 FROM actions WHERE run_id=? AND action_id=?',r.id,b.actionId))return json(view(await own(r.id)));assert(r.status==='playing','Run already ended');assert(r.revision===b.revision,'Run changed. Reload and retry.');const s=JSON.parse(r.state),a=b.action,g=games[r.game],now=Date.now(),elapsed=activeElapsed(r,now);assert(a&&typeof a.type==='string');
 if(a.type==='pause'){assert(r.active_since!==null,'Run is already paused');r.elapsed=elapsed;r.active_since=null;}else if(a.type==='resume'){assert(r.active_since===null,'Run is already active');r.active_since=now;}else if(a.type==='abandon')s.status='abandoned';else{assert(r.active_since!==null,'Resume before playing');if(['hint','replay'].includes(a.type))r.assisted=1;if(a.type==='hint'){assert(g.hint,'Hints unavailable');s.hint=g.hint(s);s.message=s.hint===null?'Restart to recover a solvable position.':'Hint shown. Rewards reduced to 25%.';}else if(a.type==='undo'){assert(g.undo,'Undo unavailable');g.undo(s);}else g.step(s,a,{elapsed});}
 if(s.status!=='playing'){r.status=s.status;r.ended_at=now;r.elapsed=elapsed;r.active_since=null;r.summary=JSON.stringify(g.summary(s));r.reward=JSON.stringify(rewardFor(g.summary(s),r));}
 const batch=await db.batch([
 stmt("INSERT OR IGNORE INTO actions(run_id,action_id,revision,timestamp,action) SELECT id,?,?,?,? FROM runs WHERE id=? AND user_id=? AND revision=? AND status='playing'",b.actionId,r.revision+1,now,JSON.stringify(a),r.id,user,r.revision),
 stmt('UPDATE runs SET state=?,status=?,elapsed=?,active_since=?,ended_at=?,assisted=?,summary=?,reward=?,revision=revision+1 WHERE id=? AND user_id=? AND revision=? AND EXISTS(SELECT 1 FROM actions WHERE run_id=? AND action_id=? AND revision=?)',JSON.stringify(s),r.status,r.elapsed,r.active_since,r.ended_at,r.assisted,r.summary,r.reward,r.id,user,r.revision,r.id,b.actionId,r.revision+1)]);
 if(!batch[1].meta.changes&&!(await get('SELECT 1 FROM actions WHERE run_id=? AND action_id=?',r.id,b.actionId)))return json({error:'Run changed. Reload and retry.'},409);return json(view(await own(r.id)));}
 if(url.pathname==='/api/shop'&&request.method==='POST'){const b=await readBody(request),item=CATALOG.find(i=>i.id===b.id);assert(item,'Unknown cosmetic');await db.batch([stmt('INSERT OR IGNORE INTO inventory(user_id,item_id,purchased_at,cost) SELECT user_id,?,?,? FROM profiles WHERE user_id=? AND crystals>=?',item.id,new Date().toISOString(),item.cost,user,item.cost),stmt('UPDATE profiles SET equipped=json_set(equipped,?,?) WHERE user_id=? AND EXISTS(SELECT 1 FROM inventory WHERE user_id=? AND item_id=?)','$.'.concat(item.kind),item.id,user,user,item.id)]);const owned=await get('SELECT 1 FROM inventory WHERE user_id=? AND item_id=?',user,item.id);assert(owned,'More crystals needed');return json({ok:true});}
 if(url.pathname.startsWith('/api/'))return json({error:'Not found'},404);if(!['GET','HEAD'].includes(request.method))return json({error:'Method not allowed'},405);if(!env.ASSETS)return json({error:'Assets unavailable'},503);const asset=await env.ASSETS.fetch(request),response=new Response(asset.body,asset);for(const [k,v] of Object.entries(security))response.headers.set(k,v);return response;
 }catch(e){const message=e?.message||'Request failed';if(/SQLITE|D1_|database|binding/i.test(message)){console.error('Prism storage operation failed');return json({error:'Progress could not be saved. Keep this screen open and retry.'},503);}return json({error:message},400);}}};
