import {fileURLToPath} from 'node:url';process.chdir(fileURLToPath(new URL('../',import.meta.url)));
import {createRequire} from 'node:module';import {resolve} from 'node:path';import {createApp} from '../server/index.mjs';import {games} from '../public/registry.mjs';import assert from 'node:assert/strict';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');
const app=createApp({local:true,dbPath:resolve('artifacts/test-db-edges-'+Date.now()+'.sqlite'),origin:'http://127.0.0.1:4318'});await new Promise(r=>app.server.listen(4318,'127.0.0.1',r));const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined});const p=await b.newPage({viewport:{width:1360,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const goto=()=>p.goto('http://127.0.0.1:4318');const click=sel=>p.locator(sel).click();const current=()=>app.db.prepare('select * from runs order by started_at desc limit 1').get();async function started(id,practice=false){await goto();if(await p.locator('#leave-paused').count())await click('#leave-paused');await p.getByRole('button',{name:'Play '+games[id].meta.name,exact:true}).click();if(practice)await p.locator('#mode').selectOption('practice');await click('#begin');await p.locator('#field').waitFor();}
try{
for(const id of Object.keys(games)){await goto();if(await p.locator('#leave-paused').count())await click('#leave-paused');await p.getByRole('button',{name:'Play '+games[id].meta.name,exact:true}).click();await click('#try');await p.locator('#field').waitFor();assert.equal(await p.locator('#real').count(),1);await click('#real');await click('#begin');await p.locator('#field').waitFor();const first=current();await click('#pause');await p.locator('#resume').waitFor();assert.equal(current().active_since,null);await click('#resume');await p.locator('#pause').waitFor();await click('#restart');await p.waitForFunction(()=>document.querySelector('#field')&&!document.querySelector('.overlay'));await p.waitForTimeout(100);const restart=current();assert.notEqual(restart.id,first.id);assert.equal(restart.seed,first.seed);assert.equal(app.db.prepare('select status from runs where id=?').get(first.id).status,'abandoned');await click('#exit');await p.getByRole('button',{name:'Play '+games[id].meta.name,exact:true}).waitFor();console.log('PASS tutorial/pause/restart/exit',id);}
await started('relay');let r=current();const state=JSON.parse(r.state),hint=games.relay.solve(state)[0];await click('#hint');await p.waitForTimeout(100);assert.equal(current().assisted,1);assert.deepEqual(JSON.parse(current().state).cells,state.cells);await click(`[data-tile="${hint}"]`);await p.waitForTimeout(100);if(current().status==='playing'){await click('#undo');await p.waitForTimeout(100);assert.deepEqual(JSON.parse(current().state).cells,state.cells);}
await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.locator('#resume').waitFor();const paused=current().elapsed;await p.waitForTimeout(200);assert.equal(current().elapsed,paused);await p.reload();await p.locator('#resume').waitFor();await click('#resume');await p.locator('#pause').waitFor();await click('#exit');
await started('lumen',true);r=current();const seed=JSON.parse(r.state).board.find(x=>x.type==='blue'),box=await p.locator('#loom').boundingBox();await p.locator('#loom').scrollIntoViewIfNeeded();const cdp=await p.context().newCDPSession(p),revisionBefore=current().revision;const x0=box.x+20,y0=box.y+20;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x0,y:y0,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x0+40,y:y0+30,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x0+40,y:y0+30,id:1},{x:x0+70,y:y0+60,id:2}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});await p.waitForTimeout(100);assert.equal(current().revision,revisionBefore);await cdp.detach();console.log('PASS actual touch cancellation and multitouch isolation');const beforeResize=current().revision;await p.mouse.move(box.x+25,box.y+25);await p.mouse.down();await p.mouse.move(box.x+70,box.y+55);await p.setViewportSize({width:1359,height:950});await p.mouse.up();await p.waitForTimeout(100);assert.equal(current().revision,beforeResize);await p.setViewportSize({width:1360,height:950});console.log('PASS drawing cancelled on resize');const pt=(x,y)=>({x:box.x+x/600*box.width,y:box.y+y/440*box.height});const pts=[pt(seed.x-18,seed.y-18),pt(seed.x+18,seed.y-18),pt(seed.x+18,seed.y+18),pt(seed.x-18,seed.y+18)];await p.mouse.move(pts[0].x,pts[0].y);await p.mouse.down();for(const q of pts.slice(1))await p.mouse.move(q.x,q.y,{steps:4});await p.mouse.up();await p.waitForTimeout(150);assert.equal(JSON.parse(current().state).score,10);
let failed=false;await p.route('**/api/runs/*/actions',async route=>{if(!failed&&route.request().postDataJSON()?.action?.type==='finish'){failed=true;await route.fetch();await route.abort('failed');}else await route.continue();});await click('#finish');await p.locator('#retry').waitFor();assert.equal(current().status,'completed');const xp=app.db.prepare('select xp from profiles where user_id=?').get('local-owner').xp;await click('#retry');await p.locator('#again').waitFor();assert.equal(app.db.prepare('select xp from profiles where user_id=?').get('local-owner').xp,xp);await p.reload();await p.getByRole('button',{name:'Play Lumen Loom',exact:true}).waitFor();assert.equal(app.db.prepare('select xp from profiles where user_id=?').get('local-owner').xp,xp);console.log('PASS response-loss/retry/refresh reward idempotence');
await p.getByRole('button',{name:'History',exact:true}).click();await p.locator('#filter-game').selectOption('lumen');await p.locator('#filter-result').selectOption('completed');assert.ok(await p.locator('[data-detail]').count());await p.locator('[data-detail]').first().click();const download=p.waitForEvent('download');await click('#export');assert.ok((await download).suggestedFilename().endsWith('.json'));console.log('PASS history filters and export');
app.db.prepare('update profiles set crystals=100 where user_id=?').run('local-owner');await p.getByRole('button',{name:'Rewards',exact:true}).click();await click('[data-buy="palette-violet"]');await p.waitForTimeout(150);await p.reload();await p.getByRole('button',{name:'Rewards',exact:true}).click();assert.equal(await p.locator('[data-buy="palette-violet"]').isDisabled(),true);assert.equal(app.db.prepare('select crystals from profiles where user_id=?').get('local-owner').crystals,65);console.log('PASS equipment reload and one-time purchase');
for(const width of [320,768,1440]){await p.setViewportSize({width,height:1000});await p.getByRole('button',{name:'Play',exact:true}).click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await p.screenshot({path:`artifacts/collection-${width}.png`,fullPage:true});}await p.emulateMedia({reducedMotion:'reduce'});await p.getByRole('button',{name:'Settings',exact:true}).click();await p.locator('#sound').check();await p.locator('#motion').check();assert.equal(errors.length,0,errors.join('\n'));console.log('PASS responsive widths, settings, no browser exceptions');
}catch(e){await p.screenshot({path:'artifacts/FAIL-edge.png',fullPage:true});throw e;}finally{await b.close();await app.close();}
