import {fileURLToPath} from 'node:url';process.chdir(fileURLToPath(new URL('../',import.meta.url)));
import {createRequire} from 'node:module';import {resolve} from 'node:path';import {createApp} from '../server/index.mjs';import {games} from '../public/registry.mjs';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
const req=createRequire(import.meta.url);const {chromium}=req(process.env.PLAYWRIGHT_MODULE||'playwright');
const app=createApp({local:true,dbPath:resolve('artifacts/test-db-complete-'+Date.now()+'.sqlite')});await new Promise(r=>app.server.listen(4317,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||undefined});const failures=[],results=[];
async function state(page){return page.evaluate(async()=>{const id=JSON.parse(localStorage.getItem('prism-active'))||window.__prismTestRun;window.__prismTestRun=id;return(await fetch('/api/runs/'+id)).json();});}
async function waitAction(page,revision){const deadline=Date.now()+8000;while(Date.now()<deadline){const r=await state(page),pending=await page.evaluate(()=>JSON.parse(localStorage.getItem('prism-pending')||'null'));if(r.revision>revision&&!pending){await page.waitForTimeout(100);return;}await page.waitForTimeout(50);}throw new Error('Action did not reach a saved UI state');}
async function act(page,fn){const r=await state(page);await fn();await waitAction(page,r.revision);}
async function stroke(page,sel,points,mobile){await page.locator(sel).scrollIntoViewIfNeeded();const box=await page.locator(sel).boundingBox(),p=points.map(v=>({x:box.x+v.x/600*box.width,y:box.y+v.y/440*box.height}));if(mobile){const cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p[0],id:1}]});for(const v of p.slice(1))await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...v,id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await cdp.detach();}else{await page.mouse.move(p[0].x,p[0].y);await page.mouse.down();for(const v of p.slice(1))await page.mouse.move(v.x,v.y,{steps:3});await page.mouse.up();}}
async function start(page,id,mode){await page.goto('http://127.0.0.1:4317');if(await page.locator('#resume').count()){await page.locator('#leave-paused')[page.__mobile?'tap':'click']();}if(await page.locator('#done').count())await page.locator('#done')[page.__mobile?'tap':'click']();await page.getByRole('button',{name:'Play '+games[id].meta.name,exact:true})[page.__mobile?'tap':'click']();if(mode)await page.locator('#mode').selectOption(mode);await page.locator('#begin')[page.__mobile?'tap':'click']();await page.locator('#field').waitFor();}
async function solveUI(page,id,mobile){let r=await state(page);const g=games[id];if(id==='lumen'){const p=r.state.board.find(p=>p.type==='blue');await act(page,()=>stroke(page,'#loom',[{x:p.x-17,y:p.y-17},{x:p.x+17,y:p.y-17},{x:p.x+17,y:p.y+17},{x:p.x-17,y:p.y+17},{x:p.x-17,y:p.y-17}],mobile));await act(page,()=>page.locator('#finish')[page.__mobile?'tap':'click']());}
else if(['relay','twin','pulse','lantern','parcel','gravity','mirror','switchyard'].includes(id)){const path=g.solve(r.state);for(const move of path){await act(page,async()=>{if(id==='relay')await page.locator(`[data-tile="${move}"]`)[page.__mobile?'tap':'click']();if(id==='twin'||id==='lantern'){if(!mobile&&move<4)await page.keyboard.press(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'][move]);else await page.locator(`[data-dir="${move}"]`)[page.__mobile?'tap':'click']();}if(id==='pulse'){await page.locator(`[data-card="${move}"]`)[page.__mobile?'tap':'click']();await page.locator('#use-card')[page.__mobile?'tap':'click']();}if(id==='parcel'){await page.locator(`[data-piece="${move.piece}"]`)[page.__mobile?'tap':'click']();if(move.vertical)await page.locator('#rotate')[page.__mobile?'tap':'click']();await page.locator(`[data-square="${move.p}"]`)[page.__mobile?'tap':'click']();}if(id==='gravity')await page.locator(`[data-thrust="${move}"]`)[page.__mobile?'tap':'click']();if(id==='mirror'){const mirror=page.locator(`[data-mirror="${move}"]`);if(mobile)await mirror.tap();else{await mirror.focus();await page.keyboard.press('Enter');}}if(id==='switchyard'){await page.locator(`[data-stack="${move.from}"]`)[page.__mobile?'tap':'click']();await page.locator(`[data-stack="${move.to}"]`)[page.__mobile?'tap':'click']();}});}}
else if(id==='cipher'){for(let i=0;i<3;i++)await act(page,()=>page.locator(`[data-feature="${i}"]`)[page.__mobile?'tap':'click']());r=await state(page);const candidate=r.state.candidates.find(c=>r.state.tests.every(t=>c.features[t.feature]===t.value));await act(page,()=>page.locator(`[data-guess="${candidate.id}"]`)[page.__mobile?'tap':'click']());}
else if(id==='signal'){for(let i=0;i<30;i++){r=await state(page);if(r.state.ack!==Math.floor(r.state.index/5))await act(page,()=>page.locator('#ack')[page.__mobile?'tap':'click']());r=await state(page);await act(page,()=>page.locator(`[data-bin="${g.answer(r.state)}"]`)[page.__mobile?'tap':'click']());}}
else if(id==='tempo'){for(let i=0;i<18;i++){r=await state(page);const n=r.state.notes[r.state.index];await act(page,()=>page.locator(n.rest?'#skip-rest':`[data-lane="${n.lane}"]`)[page.__mobile?'tap':'click']());}}
else if(id==='comet'){for(let i=0;i<12;i++){r=await state(page);const t=g.target(r.state,0);await page.locator('#comet-field').scrollIntoViewIfNeeded();const box=await page.locator('#comet-field').boundingBox();await act(page,()=>mobile?page.touchscreen.tap(box.x+t.x/600*box.width,box.y+t.y/440*box.height):page.mouse.click(box.x+t.x/600*box.width,box.y+t.y/440*box.height));}}
else if(id==='stillwater'){for(let i=0;i<5;i++){r=await state(page);const a=r.state.points[i],b=r.state.points[i+1];await act(page,()=>stroke(page,'#water',[a,{x:(a.x+b.x)/2,y:(a.y+b.y)/2},b],mobile));}}
else if(id==='recall'){const answer=[...r.state.answer];await act(page,()=>page.locator('#hide-memory')[page.__mobile?'tap':'click']());for(let i=0;i<answer.length;i++){await page.locator(`[data-symbol="${i}"]`)[page.__mobile?'tap':'click']();await act(page,()=>page.locator(`[data-memory-cell="${answer[i]}"]`)[page.__mobile?'tap':'click']());}await act(page,()=>page.locator('#check-memory')[page.__mobile?'tap':'click']());}
else if(id==='orbit'){for(let stage=0;stage<6;stage++){r=await state(page);await page.waitForTimeout(Math.max(0,r.state.readyAt-r.elapsed+150));for(const pos of r.state.sequence)await act(page,()=>page.locator(`[data-pos="${pos}"]`)[page.__mobile?'tap':'click']());}}
r=await state(page);assert.equal(r.status,'completed',`${id} completion`);await page.locator('#again').waitFor();assert.ok(r.reward&&r.reward.xp>0);return r;}
try{for(const mobile of process.env.TOUCH_ONLY?[true]:[false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},hasTouch:mobile,isMobile:mobile,deviceScaleFactor:1,reducedMotion:mobile?'reduce':'no-preference'}),page=await context.newPage(),errors=[];page.__mobile=mobile;if(process.env.DEBUG_TOUCH){page.on('console',m=>console.log('BROWSER',m.text()));page.on('request',r=>{if(r.url().includes('/actions'))console.log('REQUEST',r.postData());});await page.addInitScript(()=>{for(const type of ['pointerdown','pointerup','touchstart','touchend','click','blur'])document.addEventListener(type,e=>console.log('EVENT',type,e.target.id,e.clientX,e.clientY),true);});}page.on('pageerror',e=>errors.push(e.message));for(const id of process.env.GAME_FILTER?process.env.GAME_FILTER.split(','):Object.keys(games)){try{const mode=['lumen','signal','tempo','comet'].includes(id)?'practice':undefined;await start(page,id,mode);const r=await solveUI(page,id,mobile);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,`${id} horizontal overflow`);assert.equal(errors.length,0,errors.join('\n'));if(['lumen','twin','pulse','orbit'].includes(id))await page.screenshot({path:`artifacts/${id}-${mobile?'mobile':'desktop'}-result.png`,fullPage:true});results.push({game:id,device:mobile?'touch':'desktop',status:'PASSED',score:r.summary.metric});console.log('PASS',mobile?'touch':'desktop',id,r.summary.metric);await page.locator('#done')[page.__mobile?'tap':'click']();}catch(e){failures.push({game:id,device:mobile?'touch':'desktop',error:e.message});console.log('FAIL',mobile?'touch':'desktop',id,e.message);await page.screenshot({path:`artifacts/FAIL-${id}-${mobile?'mobile':'desktop'}.png`,fullPage:true});break;}}
await page.goto('http://127.0.0.1:4317');if(await page.locator('#leave-paused').count())await page.locator('#leave-paused')[page.__mobile?'tap':'click']();await page.screenshot({path:`artifacts/collection-${mobile?'mobile':'desktop'}.png`,fullPage:true});await context.close();}
const {writeFileSync}=await import('node:fs');writeFileSync('artifacts/browser-report.json',JSON.stringify({results,failures},null,2));if(failures.length)throw new Error(`${failures.length} browser failures`);console.log(`${results.length} requested full UI playthroughs passed.`);}finally{await browser.close();await app.close();}
