import {fileURLToPath} from 'node:url';process.chdir(fileURLToPath(new URL('../',import.meta.url)));
import {createRequire} from 'node:module';import {resolve} from 'node:path';import {createApp} from '../server/index.mjs';import assert from 'node:assert/strict';import {games} from '../public/registry.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.PLAYWRIGHT_MODULE||'playwright');let offset=0;const app=createApp({local:true,dbPath:resolve('artifacts/test-db-timing-'+Date.now()+'.sqlite'),origin:'http://127.0.0.1:4319',clock:()=>Date.now()+offset});await new Promise(r=>app.server.listen(4319,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||undefined});const p=await browser.newPage({viewport:{width:1360,height:950}});await p.clock.install();const errors=[];p.on('pageerror',e=>errors.push(e.message));const current=()=>app.db.prepare('select * from runs order by started_at desc limit 1').get();const state=()=>JSON.parse(current().state);const settle=()=>new Promise(r=>setTimeout(r,110));const click=async sel=>{await p.locator(sel).click();await settle();};async function advance(ms){offset+=ms;await p.clock.fastForward(ms);await settle();}async function start(id,mode,difficulty='normal'){await p.goto('http://127.0.0.1:4319');if(await p.locator('#leave-paused').count())await click('#leave-paused');await p.getByRole('button',{name:'Play '+games[id].meta.name,exact:true}).click();await p.locator('#difficulty').selectOption(difficulty);if(mode)await p.locator('#mode').selectOption(mode);await click('#begin');await p.locator('#field').waitFor();}
async function expectFailed(){await p.locator('#again').waitFor();assert.equal(current().status,'failed');assert.equal(JSON.parse(current().reward).xp,0);await click('#done');}
try{await start('lumen','practice');await click('#finish');await expectFailed();console.log('PASS Lumen zero-score failure');
await start('orbit');for(let i=0;i<2;i++){let s=state();await advance(Math.max(0,s.readyAt-(Date.now()+offset-current().started_at))+150);s=state();await p.keyboard.press(String((s.answer[0]+1)%8+1));await settle();assert.equal(state().phase,'reveal');await click('#next-round');}await expectFailed();console.log('PASS Orbit error reveal and failure');
await start('cipher');await click(`[data-guess="${(state().secret+1)%8}"]`);await expectFailed();
await start('signal','practice');for(let i=0;i<30;i++){if(state().ack!==Math.floor(state().index/5))await click('#ack');await click(`[data-bin="${(games.signal.answer(state())+1)%3}"]`);}await expectFailed();
await start('tempo','practice');for(let i=0;i<18;i++)await click('#skip-rest');await expectFailed();
await start('recall','practice');const answer=[...state().answer];await click('#hide-memory');for(let i=0;i<answer.length;i++){await click(`[data-symbol="${i}"]`);await click(`[data-memory-cell="${(answer[i]+1)%9}"]`);}await click('#check-memory');await expectFailed();console.log('PASS Cipher / Signal / Tempo / Recall failure screens');
await start('comet','chase');await advance(31000);await expectFailed();console.log('PASS Comet deadline with frame jump');
await start('lumen','rush');await advance(76000);await expectFailed();console.log('PASS 75-second Rush with frame jump');
await start('tempo','rhythm');const notes=[...state().notes];for(const n of notes){const elapsed=Date.now()+offset-current().started_at;await advance(Math.max(0,n.at-elapsed));if(!n.rest){await p.keyboard.press(String(n.lane+1));await settle();}}await advance(700);await p.locator('#again').waitFor();assert.equal(current().status,'completed');assert.equal(state().hits,18);await click('#done');console.log('PASS timed rhythm full completion using keyboard');
await start('orbit','stages','expert');for(let stage=0;stage<6;stage++){const s=state();await advance(Math.max(0,s.readyAt-(Date.now()+offset-current().started_at))+160);for(const i of s.answer){await p.keyboard.press(String(i+1));await settle();}}await p.locator('#again').waitFor();assert.equal(current().status,'completed');assert.equal(state().mistakes,0);console.log('PASS expert Orbit reflected stages by keyboard');assert.equal(errors.length,0,errors.join('\n'));
}catch(e){await p.screenshot({path:'artifacts/FAIL-timing.png',fullPage:true});throw e;}finally{await browser.close();await app.close();}
