import {activeElapsed,serializeRun,startFlags,restartPolicy} from './run-policy.mjs';
import http from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {games,roster} from '../public/registry.mjs';
import {clone,hash,VERSION,assert} from '../public/core.mjs';
import {openDatabase,transaction,CATALOG,finishRun} from './store.mjs';
import {authSystem} from './auth.mjs';
import {publicAuthSystem} from './public-auth.mjs';
const ROOT=fileURLToPath(new URL('../',import.meta.url));
export function createApp({local=false,dbPath=resolve(ROOT,'data/prism.sqlite'),origin='http://127.0.0.1:4317',clock=Date.now,authConfig={}}={}){
 const db=openDatabase(dbPath),auth=authConfig.publicAccess?publicAuthSystem(db):authSystem(db,{local,origin,...authConfig}),limits=new Map();
 const publicRun=r=>r?serializeRun(r,clock()):null;
 const runFor=(id,user)=>{const r=db.prepare('SELECT * FROM runs WHERE id=? AND user_id=?').get(id,user);assert(r,'Run not found');return r;};
 const end=(r,s,status)=>{r.status=status;r.ended_at=clock();r.elapsed=activeElapsed(r,clock());r.active_since=null;s.status=status;const summary=games[r.game].summary(s);db.prepare('UPDATE runs SET status=?,ended_at=?,elapsed=?,active_since=NULL,state=?,summary=? WHERE id=?').run(status,r.ended_at,r.elapsed,JSON.stringify(s),JSON.stringify(summary),r.id);const reward=finishRun(db,r,s,summary);db.prepare('UPDATE runs SET reward=? WHERE id=?').run(JSON.stringify(reward),r.id);};
 async function body(req){let text='';for await(const chunk of req){text+=chunk;if(text.length>180000)throw new Error('Request too large');}return text?JSON.parse(text):{};}
 const server=http.createServer(async(req,res)=>{res.setHeader('Cache-Control','no-store');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; script-src 'self'; connect-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'");
 const json=(x,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(x));};
 try{const url=new URL(req.url,origin);if(local&&!['127.0.0.1','localhost'].includes((req.headers.host||'').split(':')[0]))return json({error:'Local access only'},403);if(req.method!=='GET'&&req.method!=='HEAD'&&((req.headers.origin&&req.headers.origin!==origin)||req.headers['sec-fetch-site']==='cross-site'))return json({error:'Cross-origin request rejected'},403);
 if(url.pathname==='/health')return json({ok:true,private:!authConfig.publicAccess,identityConfigured:local||auth.ready});if(await auth.route(req,res,url))return;const user=auth.identify(req);if(!user){if(url.pathname.startsWith('/api/'))return json({error:'Sign in required'},401);res.writeHead(auth.ready?401:503,{'content-type':'text/html'});return res.end('<!doctype html><title>Prism Playground · Private</title><body style="background:#0c1022;color:#f3f5ff;font:18px system-ui;padding:10vw"><h1>Prism Playground</h1><p>This arcade is private.</p>'+ (auth.ready?'<a href="/auth/login" style="color:#71efc5">Sign in with your existing account</a>':'<p>Secure hosting setup is not complete. No playable content is exposed.</p>')+'</body>');}
 db.prepare('INSERT OR IGNORE INTO profiles(user_id,created_at) VALUES(?,?)').run(user,new Date(clock()).toISOString());
 if(req.method!=='GET'){const bucket=limits.get(user)||{time:clock(),n:0};if(clock()-bucket.time>60000){bucket.time=clock();bucket.n=0;}assert(++bucket.n<=600,'Too many requests. Please wait.');limits.set(user,bucket);}
 if(url.pathname==='/api/profile'){const p=db.prepare('SELECT * FROM profiles WHERE user_id=?').get(user);return json({...p,user_id:undefined,equipped:JSON.parse(p.equipped),local,inventory:db.prepare('SELECT item_id FROM inventory WHERE user_id=?').all(user).map(x=>x.item_id),achievements:db.prepare('SELECT achievement,awarded_at FROM achievements WHERE user_id=?').all(user),catalog:CATALOG});}
 if(url.pathname==='/api/challenges'){const day=new Date(clock()).toISOString().slice(0,10),g=roster[hash(day)%roster.length];return json({day,game:g.id,difficulty:'normal',completed:db.prepare('SELECT challenge FROM challenges WHERE user_id=? AND day=?').all(user,day).map(x=>x.challenge)});}
 if(url.pathname==='/api/runs'&&req.method==='GET')return json(db.prepare('SELECT * FROM runs WHERE user_id=? ORDER BY started_at DESC LIMIT 1000').all(user).map(publicRun));
 if(url.pathname==='/api/runs'&&req.method==='POST'){const bodyValue=await body(req),g=games[bodyValue.game],flags=startFlags(bodyValue);assert(g,'Unknown game');assert(['calm','normal','expert'].includes(bodyValue.difficulty),'Unknown difficulty');assert(g.meta.modes.includes(bodyValue.mode),'Unknown mode');return json(transaction(db,()=>{const day=new Date(clock()).toISOString().slice(0,10),restart=flags.restart?runFor(bodyValue.restartId,user):null,policy=restart?restartPolicy(restart,bodyValue):null;if(bodyValue.daily)assert(roster[hash(day)%roster.length].id===bodyValue.game&&bodyValue.difficulty==='normal'&&bodyValue.mode===g.meta.modes[0],'Daily challenge settings do not match');let daily=bodyValue.daily?day:null,seed;if(bodyValue.daily){db.prepare('INSERT OR IGNORE INTO daily_seeds VALUES(?,?,?)').run(day,bodyValue.game,randomUUID());seed=db.prepare('SELECT seed FROM daily_seeds WHERE day=? AND game=?').get(day,bodyValue.game).seed;}else if(restart){seed=restart.seed;if(restart.daily===day&&db.prepare('SELECT 1 FROM daily_seeds WHERE day=? AND game=? AND seed=?').get(day,bodyValue.game,seed))daily=day;}else seed=flags.replay?bodyValue.replaySeed:randomUUID();const practice=policy?policy.practice:bodyValue.mode==='practice'||flags.replay,assisted=(policy?policy.assisted:0)||(daily&&db.prepare('SELECT 1 FROM runs WHERE user_id=? AND game=? AND seed=? LIMIT 1').get(user,bodyValue.game,seed)?1:0);for(const old of db.prepare("SELECT * FROM runs WHERE user_id=? AND status='playing'").all(user))end(old,JSON.parse(old.state),'abandoned');const state=g.create(seed,bodyValue.difficulty,bodyValue.mode),id=randomUUID();db.prepare('INSERT INTO runs(id,user_id,game,version,difficulty,mode,seed,started_at,active_since,state,status,practice,assisted,daily) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,user,bodyValue.game,VERSION,bodyValue.difficulty,bodyValue.mode,seed,clock(),clock(),JSON.stringify(state),'playing',practice?1:0,assisted,daily);return publicRun(runFor(id,user));}),201);}
 const match=url.pathname.match(/^\/api\/runs\/([a-f0-9-]+)(?:\/(actions|export))?$/);if(match){let r=runFor(match[1],user);if(req.method==='GET'){const result=publicRun(r);if(match[2]==='export'){assert(r.status!=='playing','Finish the run to export');result.actions=db.prepare('SELECT revision,timestamp,action FROM actions WHERE run_id=? ORDER BY revision').all(r.id).map(a=>({...a,action:JSON.parse(a.action)}));}return json(result);}assert(match[2]==='actions'&&req.method==='POST');const b=await body(req);assert(typeof b.actionId==='string'&&/^[a-f0-9-]{36}$/.test(b.actionId),'Action ID required');return json(transaction(db,()=>{r=runFor(r.id,user);if(db.prepare('SELECT 1 FROM actions WHERE run_id=? AND action_id=?').get(r.id,b.actionId))return publicRun(runFor(r.id,user));assert(r.status==='playing','Run already ended');assert(b.revision===r.revision,'Run changed. Reload and retry.');const a=b.action,s=JSON.parse(r.state),g=games[r.game],elapsed=activeElapsed(r,clock());assert(a&&typeof a.type==='string');if(a.type==='pause'){assert(r.active_since!==null,'Run is already paused');r.elapsed=elapsed;r.active_since=null;}else if(a.type==='resume'){assert(r.active_since===null,'Run is already active');r.active_since=clock();}else if(a.type==='abandon'){end(r,s,'abandoned');}else{assert(r.active_since!==null,'Resume before playing');if(a.type==='hint'||a.type==='replay')r.assisted=1;if(a.type==='hint'){assert(g.hint,'Hints not available');s.hint=g.hint(s);s.message=s.hint===null?'Restart to recover a solvable position.':'Hint shown. Rewards reduced to 25%.';}else if(a.type==='undo'){assert(g.undo,'Undo not available');g.undo(s);}else{g.step(s,a,{elapsed});}if(s.status!=='playing')end(r,s,s.status);}
 db.prepare('UPDATE runs SET state=?,elapsed=?,active_since=?,assisted=?,revision=revision+1 WHERE id=?').run(JSON.stringify(s),r.elapsed,r.active_since,r.assisted,r.id);db.prepare('INSERT INTO actions VALUES(?,?,?,?,?)').run(r.id,b.actionId,r.revision+1,clock(),JSON.stringify(a));return publicRun(runFor(r.id,user));}));}
 if(url.pathname==='/api/shop'&&req.method==='POST'){const b=await body(req),item=CATALOG.find(x=>x.id===b.id);assert(item,'Unknown cosmetic');return json(transaction(db,()=>{const owned=item.cost===0||!!db.prepare('SELECT 1 FROM inventory WHERE user_id=? AND item_id=?').get(user,item.id);if(!owned){const p=db.prepare('SELECT crystals FROM profiles WHERE user_id=?').get(user);assert(p.crystals>=item.cost,'More crystals needed');db.prepare('UPDATE profiles SET crystals=crystals-? WHERE user_id=?').run(item.cost,user);db.prepare('INSERT INTO inventory VALUES(?,?,?)').run(user,item.id,new Date(clock()).toISOString());}const eq=JSON.parse(db.prepare('SELECT equipped FROM profiles WHERE user_id=?').get(user).equipped);eq[item.kind]=item.id;db.prepare('UPDATE profiles SET equipped=? WHERE user_id=?').run(JSON.stringify(eq),user);return {ok:true};}));}
 if(url.pathname.startsWith('/api/'))return json({error:'Not found'},404);if(req.method!=='GET'&&req.method!=='HEAD')return json({error:'Method not allowed'},405);const name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1)),base=resolve(ROOT,'public'),path=resolve(base,name);if(!path.startsWith(base+'\\')&&!path.startsWith(base+'/'))return json({error:'Not found'},404);const ext=extname(path),mime={'.html':'text/html','.mjs':'text/javascript','.css':'text/css','.svg':'image/svg+xml'}[ext];if(!mime)return json({error:'Not found'},404);res.writeHead(200,{'content-type':mime});res.end(await readFile(path));
 }catch(e){if(res.headersSent){res.end();return;}json({error:e.code==='ENOENT'?'Not found':e.message},e.code==='ENOENT'?404:400);}});
 return {server,db,close:()=>new Promise(r=>server.close(()=>{db.close();r();}))};}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){const local=process.argv.includes('--local');if(!local&&(!process.env.DB_PATH||!process.env.APP_ORIGIN))throw new Error('Production requires APP_ORIGIN and a verified durable DB_PATH');const port=Number(process.env.PORT||4317),app=createApp({local,dbPath:process.env.DB_PATH||resolve(ROOT,'data/prism.sqlite'),origin:process.env.APP_ORIGIN||`http://127.0.0.1:${port}`,authConfig:{issuer:process.env.OIDC_ISSUER,clientId:process.env.OIDC_CLIENT_ID,allowed:process.env.OIDC_ALLOWED_SUBJECTS}});app.server.listen(port,local?'127.0.0.1':'0.0.0.0',()=>console.log(`Prism Playground ${local?'local private development':'production private'} server on port ${port}`));}
