import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,readFileSync} from 'node:fs';
import {dirname} from 'node:path';
export function openDatabase(path){mkdirSync(dirname(path),{recursive:true});const db=new DatabaseSync(path);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');db.exec(readFileSync(new URL('./001-schema.sql',import.meta.url),'utf8'));db.exec(readFileSync(new URL('./002-daily-seeds.sql',import.meta.url),'utf8'));return db;}
export function transaction(db,fn){db.exec('BEGIN IMMEDIATE');try{const value=fn();db.exec('COMMIT');return value;}catch(e){db.exec('ROLLBACK');throw e;}}
import {CATALOG,rewardFor} from './economy.mjs';
export {CATALOG,rewardFor};
export function finishRun(db,run,state,summary){const reward=rewardFor(summary,run),now=new Date().toISOString();if(run.status==='completed'&&!run.practice&&!run.assisted){const day=new Date(run.started_at).toISOString().slice(0,10);if(run.daily===day){const ins=db.prepare('INSERT OR IGNORE INTO challenges VALUES(?,?,?,?)').run(run.user_id,day,'daily',run.id);if(ins.changes){reward.daily=25;reward.xp+=25;reward.crystals+=5;}}
const other=db.prepare("SELECT COUNT(DISTINCT game) AS n FROM runs WHERE user_id=? AND status='completed' AND practice=0 AND assisted=0 AND started_at>=? AND started_at<?").get(run.user_id,Date.parse(day),Date.parse(day)+86400000).n;if(other>=2&&db.prepare('INSERT OR IGNORE INTO challenges VALUES(?,?,?,?)').run(run.user_id,day,'two-games',run.id).changes){reward.mission+=15;reward.xp+=15;reward.crystals+=3;}
if(summary.puzzle&&db.prepare('INSERT OR IGNORE INTO challenges VALUES(?,?,?,?)').run(run.user_id,day,'clear-puzzle',run.id).changes){reward.mission+=15;reward.xp+=15;reward.crystals+=3;}
const awards=['first-completion'];if(['orbit','recall'].includes(run.game)&&summary.accuracy===1)awards.push('perfect-memory');if(summary.puzzle&&summary.efficient)awards.push('efficient-puzzle');if(summary.chain>=6)awards.push('harmony-six');if(db.prepare("SELECT COUNT(DISTINCT game) AS n FROM runs WHERE user_id=? AND status='completed'").get(run.user_id).n>=16)awards.push('all-sixteen');for(const a of awards)db.prepare('INSERT OR IGNORE INTO achievements VALUES(?,?,?,?)').run(run.user_id,a,now,run.id);}
const inserted=db.prepare('INSERT OR IGNORE INTO reward_transactions VALUES(?,?,?,?,?,?)').run(run.id,run.user_id,reward.xp,reward.crystals,JSON.stringify(reward),now);if(inserted.changes)db.prepare('UPDATE profiles SET xp=xp+?,crystals=crystals+? WHERE user_id=?').run(reward.xp,reward.crystals,run.user_id);return reward;}
