import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,primaryKey,index,uniqueIndex,check} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{userId:text('user_id').primaryKey(),xp:integer('xp').notNull().default(0),crystals:integer('crystals').notNull().default(0),equipped:text('equipped').notNull().default('{}'),createdAt:text('created_at').notNull()},t=>[check('xp_nonnegative',sql`${t.xp} >= 0`),check('crystals_nonnegative',sql`${t.crystals} >= 0`)]);
export const runs=sqliteTable('runs',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>profiles.userId),game:text('game').notNull(),version:text('version').notNull(),difficulty:text('difficulty').notNull(),mode:text('mode').notNull(),seed:text('seed').notNull(),startedAt:integer('started_at').notNull(),endedAt:integer('ended_at'),elapsed:integer('elapsed').notNull().default(0),activeSince:integer('active_since'),state:text('state').notNull(),status:text('status').notNull(),assisted:integer('assisted').notNull().default(0),practice:integer('practice').notNull().default(0),revision:integer('revision').notNull().default(0),daily:text('daily'),summary:text('summary'),reward:text('reward')},t=>[index('runs_user_date').on(t.userId,t.startedAt)]);
export const actions=sqliteTable('actions',{runId:text('run_id').notNull().references(()=>runs.id),actionId:text('action_id').notNull(),revision:integer('revision').notNull(),timestamp:integer('timestamp').notNull(),action:text('action').notNull()},t=>[primaryKey({columns:[t.runId,t.actionId]}),uniqueIndex('actions_one_revision').on(t.runId,t.revision),index('actions_timestamp').on(t.timestamp)]);
export const rewards=sqliteTable('reward_transactions',{runId:text('run_id').primaryKey().references(()=>runs.id),userId:text('user_id').notNull(),xp:integer('xp').notNull(),crystals:integer('crystals').notNull(),breakdown:text('breakdown').notNull(),createdAt:text('created_at').notNull()});
export const inventory=sqliteTable('inventory',{userId:text('user_id').notNull(),itemId:text('item_id').notNull(),purchasedAt:text('purchased_at').notNull(),cost:integer('cost').notNull().default(0)},t=>[primaryKey({columns:[t.userId,t.itemId]})]);
export const achievements=sqliteTable('achievements',{userId:text('user_id').notNull(),achievement:text('achievement').notNull(),awardedAt:text('awarded_at').notNull(),runId:text('run_id').notNull()},t=>[primaryKey({columns:[t.userId,t.achievement]})]);
export const challenges=sqliteTable('challenges',{userId:text('user_id').notNull(),day:text('day').notNull(),challenge:text('challenge').notNull(),runId:text('run_id').notNull()},t=>[primaryKey({columns:[t.userId,t.day,t.challenge]})]);

export const dailySeeds=sqliteTable('daily_seeds',{day:text('day').notNull(),game:text('game').notNull(),seed:text('seed').notNull()},t=>[primaryKey({columns:[t.day,t.game]})]);
